apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: api-tech-challenge
  name: api-dev-rolebinding
subjects:
  - kind: User
    name: api-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: api-dev-role
  apiGroup: rbac.authorization.k8s.io