apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-deployment
spec:
  template:
    metadata:
      name: database
      labels:
        app: database-pod
    spec:
      containers:
        - name: database-container
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: database-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-pvc
      volumes:
        - name: database-pvc
          persistentVolumeClaim:
            claimName: database-pvc
  selector:
    matchLabels:
      app: database-pod
  serviceName: database-service
        