apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: database-tech-challenge
spec:
  type: NodePort
  selector:
    app: database-pod
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31000
