apiVersion: v1
kind: Secret
metadata:
  name: database-secret 
  namespace: database-tech-challenge
data:
  POSTGRES_DB: "dGVjaC1jaGFsbGVuZ2U="
  POSTGRES_USER: "dGVzdGU="
  POSTGRES_PASSWORD: "dGVzdGU="
  POSTGRES_HOST: "bG9jYWxob3N0"