apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: database-tech-challenge
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi