apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api-tech-challenge
  labels:
    app: api-service
spec:
  type: LoadBalancer
  selector:
    app: api-fiap-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000