apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: api-tech-challenge
data:
  NODE_ENV: "cHJvZHVjdGlvbg=="
  PROMETHEUS_ENDPOINT: "aHR0cDovL3Byb21ldGhldXMtc2VydmljZS5tb25pdG9yaW5nLXRlY2gtY2hhbGxlbmdlOjkwOTA="
  DB_DATABASE: "dGVjaC1jaGFsbGVuZ2U="
  DB_USERNAME: "dGVzdGU="
  DB_PASSWORD: "dGVzdGU="
  DB_HOST: "ZGF0YWJhc2Utc2VydmljZS5kYXRhYmFzZS10ZWNoLWNoYWxsZW5nZQ=="