apiVersion: v1
kind: Service
metadata:
  name: api-service-nodeport
  labels:
    app: api-service-nodeport
spec:
  type: NodePort
  selector:
    app: api-fiap-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31001