apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
data:
  NODE_ENV: "cHJvZHVjdGlvbg=="
  PROMETHEUS_ENDPOINT: "aHR0cDovL3Byb21ldGhldXMtc2VydmljZTo5MDkw"
  DB_DATABASE: "dGVjaC1jaGFsbGVuZ2U="
  DB_USERNAME: "dGVzdGU="
  DB_PASSWORD: "dGVzdGU="
  DB_HOST: "ZGF0YWJhc2Utc2VydmljZQ=="