apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-fiap-deployment
  labels:
    app: api-fiap-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-fiap-pod
  template:
    metadata:
      name: api-fiap-pod
      labels:
        app: api-fiap-pod
    spec:
      containers:
        - name: api-fiap-challenge-container
          image: gustavoclemente/api-tech-challenge-fiap:1.0.0
          ports:
            - name: api-port
              containerPort: 3000
          envFrom:
            - secretRef:
                name: api-secrets
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health
              port: api-port
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3