apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: database-tech-challenge
  name: dba-rolebinding
subjects:
  - kind: User
    name: dba-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dba-role
  apiGroup: rbac.authorization.k8s.io