apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: monitoring-tech-challenge
  name: monitoring-rolebinding
subjects:
  - kind: User
    name: monitoring-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitoring-role
  apiGroup: rbac.authorization.k8s.io