apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring-tech-challenge
  name: monitoring-role
rules:
  - apiGroups: ["*"]
    resources: ["pods", "deployments", "services", "secrets", "configMap", "persistentvolumeclaims"]
    verbs: ["list", "create", "watch", "patch", "delete", "exec", "get"]

