apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring-tech-challenge
  labels:
    app: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana-pod
  ports:
      - port: 3000
        targetPort: 3000
        nodePort: 31002