name: 'CI'
on: pull_request
jobs:
  using: "composite"
  install-deps: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: ./actions/install-deps
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps]
    steps:
      - uses: ./actions/install-deps
      - name: Run e2e tests
        run: yarn test:e2e
  lint:      
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps]
    steps:
      - uses: ./actions/install-deps
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps, tests, lint]
    steps:
      - uses: ./actions/install-deps
      - name: Run build
        run: yarn build
