name: 'CI'
on: pull_request
jobs:
  install-deps: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/install-deps-action/action
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/install-deps-action/action
      - name: Run e2e tests
        run: yarn test:e2e
  lint:      
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/install-deps-action/action
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps, tests, lint]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/install-deps-action/action
      - name: Run build
        run: yarn build
