name: 'CI'
on: 
  push:
    branches:
      - main
      - develop
      - github-actions
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  install-deps: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps]
    steps:
      - name: Run e2e tests
        run: yarn test:e2e
  lint:      
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps]
    steps:
      - name: Lint
        run: yarn lint
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: [install-deps, tests, lint]
    steps:
      - name: Run build
        run: yarn build
